### ISSUE TITLE
Building QtAutoupdater from source

### ISSUE THREAD

**Issue by IQ-raf** [Skycoder42/QtAutoUpdater#27] opened 2019-06-18 16:25 UTC
Hey, I am trying to build the latest commit of the QtAutoupdater to check if the latest fix works on Mac, build after downloading the source files from the release page and running `qmake` I get this error: 
`
/usr/local/Qt-5.12.1/mkspecs/features/qt_build_config.prf:47: shadowed(path) requires one argument.
`

I can seem to be able to run `qmake`, I also tried rerunning `qdep` but that didn't fix the issue

**Comment by Skycoder42** [comment] 2019-06-18 16:52
Thats strange. It seems some path is missing somewhere. Please uncomment the `load(qdep)`line and run qmake again. The project cannot be built that way, but at least we can find out, where the error lies. If it does not appear again, please tell me, so I can follow up with further steps

**Comment by IQ-raf** [comment] 2019-06-18 17:13
I have a new error now, it happens when I run qmake in `qtautoupdater/src` 
`
Cannot read /Users/iqinetics/Qt/5.12.1/Src/qtautoupdater/mkspecs/modules-inst/qt_lib_autoupdatercore.pri: No such file or directory`

`Cannot read /Users/iqinetics/Qt/5.12.1/Src/qtautoupdater/mkspecs/modules-inst/qt_lib_autoupdatercore_private.pri: No such file or directory`

`Cannot read /Users/iqinetics/Qt/5.12.1/Src/qtautoupdater/mkspecs/modules-inst/qt_lib_autoupdatergui.pri: No such file or directory`

`Cannot read /Users/iqinetics/Qt/5.12.1/Src/qtautoupdater/mkspecs/modules-inst/qt_lib_autoupdatergui_private.pri: No such file or directory`

`/usr/local/Qt-5.12.1/mkspecs/features/qt_build_config.prf:47: shadowed(path) requires one argument.`

there is also no  `load(qdep)` in the `qtautoupdater.pro` file, only a `load(qt_parts)`

**Comment by IQ-raf** [comment] 2019-06-18 17:18
ok changing `load(qt_parts)` with `load(qdeb)` fixed the first shadowing issue, but I still have the 

`Cannot read /Users/iqinetics/Qt/5.12.1/Src/qtautoupdater/mkspecs/modules-inst/qt_lib_autoupdatercore.pri: No such file or directory`
`Cannot read /Users/iqinetics/Qt/5.12.1/Src/qtautoupdater/mkspecs/modules-inst/qt_lib_autoupdatercore_private.pri: No such file or directory`
`Cannot read /Users/iqinetics/Qt/5.12.1/Src/qtautoupdater/mkspecs/modules-inst/qt_lib_autoupdatergui.pri: No such file or directory`
`Cannot read /Users/iqinetics/Qt/5.12.1/Src/qtautoupdater/mkspecs/modules-inst/qt_lib_autoupdatergui_private.pri: No such file or directory`

issues

**Comment by Skycoder42** [comment] 2019-06-19 07:47
you have to run `qmake` on the top level directory. I meant to change the `load(qdep)...` in `src/autoupdatercore/autoupdatercore.pro` and `src/autoupdatergui/autoupdatergui.pro`. Try to change those and then run `qmake` on toplevel again.

**Comment by IQ-raf** [comment] 2019-06-19 18:23
in ` src/autoupdatercore/autoupdatercore.pro` and ` src/autoupdatergui/autoupdatergui.pro` there is only this line related to `qdeb`:
`!load(qdep):error("Failed to load qdep feature! Run 'qdep prfgen --qmake $$QMAKE_QMAKE' to create it.")`

I tried commenting it, uncommenting it, deleting the `!`, but I still get the same error.
`Cannot read /Users/iqinetics/Qt/5.12.1/Src/qtautoupdater/mkspecs/modules-inst/qt_lib_autoupdatercore.pri: No such file or directory
Cannot read /Users/iqinetics/Qt/5.12.1/Src/qtautoupdater/mkspecs/modules-inst/qt_lib_autoupdatercore_private.pri: No such file or directory
Cannot read /Users/iqinetics/Qt/5.12.1/Src/qtautoupdater/mkspecs/modules-inst/qt_lib_autoupdatergui.pri: No such file or directory
Cannot read /Users/iqinetics/Qt/5.12.1/Src/qtautoupdater/mkspecs/modules-inst/qt_lib_autoupdatergui_private.pri: No such file or directory
/usr/local/Qt-5.12.1/mkspecs/features/qt_build_config.prf:47: shadowed(path) requires one argument.
`

**Comment by Skycoder42** [comment] 2019-06-19 19:10
Thats strange. I have never seen such an error. The thing is: on my CI-systems, it works without any of these errors, i.e. I cannot reproduce the error and thus not fix it...

**Comment by IQ-raf** [comment] 2019-06-20 19:52
Hey, I don't know why I couldn't build, but I ended up just copying your changes in your commit to the qtautoupdater folder inside Qt/Src. 

then I built from there and it fixed all my issues (even the mac updater one).

thanks again for your help !

**Comment by Skycoder42** [comment] 2019-06-20 22:44
Perfect! I will close this issue as unresolved, since the problem with build was not really resolved... Still, since your problem was resolved, I consider this done.

**Closed as completed by Skycoder42** 2019-06-20 22:44 UTC
Labels: wontfix
