### ISSUE TITLE
Unknown module(s) in QT: autoupdatercore (Qt 5.12.0 x86 compiler MSVC 2017)

### ISSUE THREAD

**Issue by nikishyn** [Skycoder42/QtAutoUpdater#18] opened 2018-12-17 09:52 UTC
Hi.
In my application I decided to update the kit Qt and the compiler.
After upgrading Qt and installing Skycoder42 Qt modules with the **QT kit 5.12.0 MSVC 2017 x32** received an error Unknown module (s) in QT: autoupdatercore. 
I do not see Qt5AutoUpdaterCore.dll in path C: \ Qt \ 5.12.0 \ msvc2017 \ bin

Please give me advice on how to fix the problem.

**Comment by Skycoder42** [comment] 2018-12-17 10:55
The reason is that beginning with a few Qt-Versions ago, Qt only shipped the x64 version of MSVC 2017. Thus I had to remove the builds as well. It seems 32 bit support has been readded with Qt 5.12 (See [QTBUG-63708](https://bugreports.qt.io/browse/QTBUG-63708)). So currently there is no prebuilt binary to be installed.

I would recommend you to switch to the x64 Version if possible. If thats not possible, you can either wait until I find the time to update my CI-scripts to provide msvc2017 builds or build the library yourself instead.

If you decide to build it yourself, open the **Visual Studio 2017 x86 command line prompt** and run the following commands inside the root directoy of this repostitory (either clone it or download the sources from the release page). Please note that you will have to install [qpmx](https://github.com/Skycoder42/qpmx) first. The easiest way is to use [Chocolatey](https://chocolatey.org/) for this: `choco install qpmx`

```
cd C:\path\to\QtAutoUpdater
C:\Qt\5.12.0\msvc2017\bin\qmake
nmake
nmake lrelease
nmake install
```

This will build the library and install it into your Qt installation. Please note that this might cause conflicts if you later decide to install the version from the maintenancetool I am planning to provide. Either ways, I will notify you here once the prebuilt msvc2017 32 bit version is available

**Comment by nikishyn** [comment] 2018-12-17 12:12
Thanks for the answer. Waiting for a version in maintenancetool .

**Comment by Skycoder42** [comment] 2018-12-19 10:15
I just uploaded the packages to my server. Please try if it now works for you. To do so, you must reinstall the package. First uncheck the module and *complete* the install to remove the documentation and examples. Then restart the Maintenancetool and install the module again. The installer should automatically detect the new binaries and install them.

**Comment by nikishyn** [comment] 2018-12-21 09:14
Hi.
I removed all components "Skycoder42 Qt modules", then restart Maintenancetool  and install Skycoder42 Qt modules 5.10.0  and 5.12.0 for MSVC2017. But component ver. 5.12.0 MSVC installed without updater module. I attached a log file when installing components. Maybe it will be useful
[Installation Details.txt](https://github.com/Skycoder42/QtAutoUpdater/files/2702197/Installation.Details.txt)

**Comment by Skycoder42** [comment] 2018-12-21 09:46
Based on the logs, it did install. Please check if you can find the files listed [here](https://github.com/Skycoder42/QtAutoUpdater/files/2702276/Installation.Details.txt).

If yes, try to delete the build folder of your project and compile the project again. On windows, qmake often fails to pick up changes outside the build directory, so QtCreator propably just assumed nothing changed it did not even check if the library exists now.

**Comment by nikishyn** [comment] 2018-12-21 13:46
After installing the module - there are no libraries in the bin folder.
I attached a file list in dir  C:\Qt\5.12.0\msvc2017\bin

[AutuUpd.txt](https://github.com/Skycoder42/QtAutoUpdater/files/2702967/AutuUpd.txt)

**Comment by Skycoder42** [comment] 2018-12-21 19:05
Thats strange. I just did a clean install on a clean virtual machine and it does work as expected. The libraries are installed as they should be.

Whatever the problem is, it is unrelated to this library. My guess is your Qt installation somehow got corrupted. Try to *completely* uninstall Qt and install everything from scratch again. I will close this issue now, as the original problem has been fixed. You can however still reply to it.

**Closed as completed by Skycoder42** 2018-12-21 19:05 UTC
Labels: enhancement, help wanted
